version: "3.9"
services:
  product:
    build: ./product-service
    deploy:
      resources:
        limits:
          memory: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  recommendation:
    build: ./recommendation-service
    deploy:
      resources:
        limits:
          memory: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  review:
    build: ./review-service
    deploy:
      resources:
        limits:
          memory: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  product-composite:
    build: ./product-composite-service
    deploy:
      resources:
        limits:
          memory: 350m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

